blank_issues_enabled: false
contact_links:
  - name: Contribution Guidelines
    url: https://github.com/PTCInc/vuforia-engine/blob/master/CONTRIBUTING.md
    about: You must follow the contribution guidelines in order to post any bug report or feedback request.
  - name: Vuforia Engine Developer Portal
    url: https://developer.vuforia.com/
    about: Access your account, download the SDK, and view account usage.
  - name: Vuforia Engine Library
    url: https://library.vuforia.com/
    about: Find detailed articles and best practices for using Vuforia Engine.
